# -*- coding: utf-8 -*-
"""Movie Recommendation System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12oKj6mOU7L491Nh7QbRr-8pRvce5VnaT
"""

!pip install pandas numpy scikit-learn

import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')

print(movies.head())

print(movies.shape)
print(ratings.shape)

movies['genres'] = movies['genres'].fillna('')

# Convert Text into Vectors

cv = CountVectorizer(max_features=5000, stop_words='english')

vector = cv.fit_transform(movies['genres']).toarray()

print(vector.shape)

similarity = cosine_similarity(vector)

print(similarity)

def recommend(movie_name):

    if movie_name not in movies['title'].values:
        print("Movie not found")
        return

    movie_index = movies[movies['title'] == movie_name].index[0]

    distances = similarity[movie_index]

    movies_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:6]

    print(f"Recommended movies for {movie_name}:\n")

    for i in movies_list:
        print(movies.iloc[i[0]].title)

recommend('Toy Story (1995)')

# Add User Input
movie_name = input("Enter movie name: ")

recommend(movie_name)

top_movies = ratings.groupby('movieId')['rating'].count()

top_movies = top_movies.sort_values(
    ascending=False
).head(10)

print(top_movies)

avg_rating = ratings.groupby('movieId')['rating'].mean()

print(avg_rating.sort_values(
    ascending=False
).head(10))

import matplotlib.pyplot as plt

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

ratings['rating'].hist(bins=10)

plt.xlabel("Rating")
plt.ylabel("Frequency")
plt.title("Distribution of Movie Ratings")

plt.show()

