# -*- coding: utf-8 -*-
"""Flipkart Reviews Sentiment Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FTdxmvym0wJZGLKqw5C4QCEBHl3pAe4c
"""

!pip install pandas numpy nltk scikit-learn seaborn matplotlib

import pandas as pd
import numpy as np
import re
import nltk
import matplotlib.pyplot as plt
import seaborn as sns

from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

nltk.download('stopwords')

from google.colab import files
uploaded = files.upload()

import io

df = pd.read_csv(io.BytesIO(uploaded['flipkart (1).csv']))
df.head()

#Create Sentiment Column (IMPORTANT)
# here what we done is loop we hvve give f rating above 4 the it will positive less then it will be negative
def get_sentiment(rating):
    if rating >= 4:
        return "positive"
    else:
        return "negative"

df["sentiment"] = df["Rating"].apply(get_sentiment)
df.head()

# Text Cleaning
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-zA-Z]', ' ', text)
    text = text.split()
    text = [word for word in text if word not in stop_words]
    return " ".join(text)

df["clean_review"] = df["Review"].apply(clean_text)

# Data Visualization
sns.countplot(x=df["sentiment"])
plt.title("Sentiment Distribution")
plt.show()

# TF-IDF Vectorization
tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(df["clean_review"]).toarray()
y = df["sentiment"]

# Train-Test Split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Model Training
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Accuracy + Report
print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(5,4))
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues')
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

def predict_sentiment(review):
    review = clean_text(review)
    vector = tfidf.transform([review]).toarray()
    return model.predict(vector)[0]

print(predict_sentiment("This laptop is amazing and fast"))
print(predict_sentiment("Very bad product, waste of money"))

